feat: support build etcd with failpoint (#2)
* feat: support build etcd with failpoint

* chore: add e2e test

* chore: fix e2e test

* chore: fix e2e test

* fix: BUILD_WITH_FAILPOINT condition

* fix: BUILD_WITH_FAILPOINT condition

* fix: vfox use when etcd build with failpoint

* opt: vfox use flow

* chore(e2e): check failpoint

* chore(e2e): fix macos go

* docs: update plugin desc

* chore: fix ci

* docs: update README

* docs: update README ref link

diff --git a/.github/workflows/e2e_test.yaml b/.github/workflows/e2e_test.yaml
--- a/.github/workflows/e2e_test.yaml
+++ b/.github/workflows/e2e_test.yaml
@@ -3,6 +3,7 @@ name: E2E tests
 on:
   push:
     branches: [main]
+  pull_request:
   workflow_dispatch:
 
 jobs:
@@ -38,8 +39,14 @@ jobs:
           scoop install vfox
 
       - name: add vfox-etcd plugin
+        if: runner.os == 'Windows'
         run: |
-          vfox add --source https://github.com/version-fox/vfox-etcd/archive/refs/heads/main.zip etcd
+          vfox add --source https://github.com/version-fox/vfox-etcd/archive/$env:GITHUB_REF.zip etcd
+
+      - name: add vfox-etcd plugin
+        if: runner.os != 'Windows'
+        run: |
+          vfox add --source https://github.com/version-fox/vfox-etcd/archive/${GITHUB_REF}.zip etcd
 
       - name: install etcd by vfox-etcd plugin (Linux)
         if: runner.os == 'Linux'
@@ -73,3 +80,50 @@ jobs:
           echo $env:PATH
           echo "===============PATH==============="
           etcd -version
+
+      - name: install etcd with failpoint by vfox-etcd plugin (Linux)
+        if: runner.os == 'Linux'
+        run: |
+          export BUILD_WITH_FAILPOINT=yes
+          vfox install etcd@3.4.32
+          vfox use -g etcd@3.4.32
+          eval "$(vfox activate bash)"
+          echo "===============PATH==============="
+          echo $PATH
+          echo "===============PATH==============="
+          etcd -version
+          export GOFAIL_HTTP="127.0.0.1:22381"
+          nohup etcd > etcd.log 2>&1 &
+          output=$(curl http://127.0.0.1:22381 | grep afterCommit)
+          if [ -n "$output" ]; then
+            echo "etcd with failpoint"
+            echo $output
+          else
+            echo "etcd does not with failpoint"
+            echo $output
+            exit 1
+          fi
+
+      - name: install etcd with failpoint by vfox-etcd plugin (MacOS)
+        if: runner.os == 'MacOS'
+        run: |
+          brew install go
+          export BUILD_WITH_FAILPOINT=yes
+          vfox install etcd@3.4.32
+          vfox use -g etcd@3.4.32
+          eval "$(vfox activate bash)"
+          echo "===============PATH==============="
+          echo $PATH
+          echo "===============PATH==============="
+          etcd -version
+          export GOFAIL_HTTP="127.0.0.1:22381"
+          nohup etcd > etcd.log 2>&1 &
+          output=$(curl http://127.0.0.1:22381 | grep afterCommit)
+          if [ -n "$output" ]; then
+            echo "etcd with failpoint"
+            echo $output
+          else
+            echo "etcd does not with failpoint"
+            echo $output
+            exit 1
+          fi
